name: Docker to Docker Hub

on: 
  push:
    branches:
      - 'main'

jobs:
  push_to_docker_hub:
    name: Push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout out the repo 
        uses: actions/checkout@v4
      
      - name: log in to docker hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_DOC }}
          password: ${{ secrets.PASSWORD_DOC }}

      - name: build image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: al-shimchenko/test:latest
